name: Android CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Run unit tests
      run: ./gradlew test

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Create AVD and start emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        arch: x86_64
        target: default 
        emulator-options: -no-window -noaudio -no-boot-anim -accel on -gpu swiftshader_indirect -skin 1080x1920
        disable-animations: false
        force-avd-creation: false
        emulator-build: 7425822 
        wait-for-boot: true
        startup-timeout: 120s 

    - name: Run instrumented tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        arch: x86_64
        target: default
        emulator-options: -no-window -noaudio -no-boot-anim -accel on -gpu swiftshader_indirect -skin 1080x1920
        disable-animations: true
        force-avd-creation: false
        emulator-build: 7425822
        wait-for-boot: false
        startup-timeout: 30s
        command: ./gradlew connectedCheck